using Volo.Abp;

namespace WorkiomProjectManagement.EntityFrameworkCore;

public abstract class WorkiomProjectManagementEntityFrameworkCoreTestBase : WorkiomProjectManagementTestBase<WorkiomProjectManagementEntityFrameworkCoreTestModule>
{

}
